### ISSUE TITLE
Alert Style breaks when changing from one to another (eg: Alert to date/time)

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#148]
Was with a member of staff who had used an alert within content for hand in. When wanting to change an alert to date/time he highlighted the area and changed to date/time. Hitting save did not apply the changes and seemed to break the original alert. 

This was on IE 10 (haven't had chance to replicate in other browsers yet)

**Comment by ghost** [comment]
I have replicated the error. This is gonna be difficult to debug as it is to do with TinyMCE (aka pile of shit), and how the plugin adds "styles" to text content.

So that you know (and can let academics know) to get around the problem:

If you have selected "Alert", for example, and want to change to "Date" you need to select "Alert" again to remove the alert styles and then select "Date."

I will have a look at fixing this, but for the time being the above is a work-around.

**Comment by ghost** [comment]
Closing as this is a training issue.
@etsupport
