### ISSUE TITLE
Reduce Empty Modules to 5 Sections (and note)

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#169]
At the moment there are a lot of modules with no content in. 20 blank modules is a bit daunting for someone who doesn't like using the LS. Can we change the default back to something more like 5?

Also think it would be good to go through and make a note of any blank modules, taking empty sections down to 5 and making a note of all of those blank modules. What does everyone think?

**Comment by Asampson** [comment]
Default will be kept to 20. We will go through with our allocated schools and change any empty to 5, and make note of blank modules. 

@damienh @oscott Amy

**Comment by Asampson** [comment]
@damienh and @themarkness have you being doing this within your departments? Seeing if I can close this issue.

**Comment by Asampson** [comment]
@damienh and @themarkness have you being doing this within your departments? Seeing if I can close this issue.

**Comment by Asampson** [comment]
@damienh and @themarkness have you being doing this within your departments? Seeing if I can close this issue.

**Comment by Asampson** [comment]
@damienh and @themarkness have you being doing this within your departments? I know from the meeting last week some of the schools has extra sections, can we check our schools so I can close this please?

**Comment by damienh** [comment]
I haven’t as of yet. I am more than happy to do this but it won’t be until either next week or early new year due to EMU validation and professional writing 14-16 going live within next 4 weeks.

On 16 Dec 2013, at 13:15, Asampson <notifications@github.com<mailto:notifications@github.com>> wrote:

@damienhhttps://github.com/damienh and @themarknesshttps://github.com/themarkness have you being doing this within your departments? I know from the meeting last week some of the schools has extra sections, can we check our schools so I can close this please?

—
Reply to this email directly or view it on GitHubhttps://github.com/ucfalmouth/issues/issues/169#issuecomment-30659447.

[Falmouth University] http://www.falmouth.ac.uk/      [Follow us]     [Facebook]  https://www.facebook.com/falmouthuni      [Twitter]  http://twitter.com/falmouthuni     [Youtube]  http://www.youtube.com/falmouthuniversity  [Pintrest]  http://pinterest.com/falmouthuni

  This email is confidential and intended solely for the use of the intended recipient only. If you have received this email in error, please inform us immediately and then delete it.

**Comment by oscott** [comment]
through testing, @aaronmarruk and myself have concluded that the central course default settings will dictate all new moodle courses and also any courses that have already been created but not over-ridden. So, firstly, now there is the + / - functionality we should default to 1 topic. But prior to doing this we have to override every course. I would recommend that in every moodle course we plus then minus a topic, to ensure that all are over ridden. unless all have gone through and tidied up already on the live site? ( @damienh @Asampson @themarkness  )

There may be a database solution, but I'm going to get started on the manual process ASAP as it's being assigned to update 2.1.

**Comment by Asampson** [comment]
You may have to explain this one to me in person because I don't understand what you mean with overriding settings etc. I've already tidied up the courses that are assigned as POC.

**Comment by oscott** [comment]
@Asampson @damienh @themarkness Will be manually checking these by Friday 21st.

**Comment by themarkness** [comment]
Done
