### ISSUE TITLE
Enable Spellcheck engine

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#270]
http://learn-dev.falmouth.ac.uk/admin/settings.php?section=tinymcespellcheckersettings needs to be enabled on dev and tested. CM has been approved by @Asampson @aaronmarruk @themarkness

**Comment by damienh** [comment]
Tried to test on dev and get error message stating pspell is not found in php installation. Its also worth noting that it adds an extra option to the text editor so it will need styling. I recommend that this gets moved to 2.2 Update. @ucfalmouth thoughts?

**Comment by Asampson** [comment]
@themarkness and AS to have a look at this.

**Comment by themarkness** [comment]
Aspell is installed on server. Have tried to link to from here and it works  http://learn-dev.falmouth.ac.uk/admin/settings.php

pspell.dll does not work with Zend implimentation of PHP. I believe this is fixed in 2.5, but may still not work for our server.  Until then Ctrl+right click enables browser spell checking.

**Comment by Asampson** [comment]
This is something that is potentially fixed in 2.7.

**Comment by oscott** [comment]
no longer using tinyMCE - no longer relevent
