### ISSUE TITLE
Scheduler email terminology refers to course not module

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#271]
Currently the terminology sent to students by email when they have booked an appointment refers to a module as a course. Requesting to change this so that module is used instead of course:

"An appointment has been applied for on 3 January 2014 at 12:10 PM,
by the student student student for the course:

MOD 101 Example Module: MOD101 Example Module"

**Comment by damienh** [comment]
1+ This.

On 2 Jan 2014, at 11:09, Asampson <notifications@github.com<mailto:notifications@github.com>> wrote:

Currently the terminology sent to students by email when they have booked an appointment refers to a module as a course. Requesting to change this so that module is used instead of course:

"An appointment has been applied for on 3 January 2014 at 12:10 PM,
by the student student student for the course:

MOD 101 Example Module: MOD101 Example Module"

—
Reply to this email directly or view it on GitHubhttps://github.com/ucfalmouth/issues/issues/271.

[Falmouth University] http://www.falmouth.ac.uk/      [Follow us]     [Facebook]  https://www.facebook.com/falmouthuni      [Twitter]  http://twitter.com/falmouthuni     [Youtube]  http://www.youtube.com/falmouthuniversity  [Pintrest]  http://pinterest.com/falmouthuni

This email is confidential and intended solely for the use of the intended recipient only. If you have received this email in error, please inform us immediately and then delete it.

**Comment by oscott** [comment]
Approved - this should just be a missed change in the language pack. - @Asampson @aaronmarruk

**Comment by Asampson** [comment]
Looking like we will be amending scheduler (#217) will wait to see what happens before altering language pack.

**Comment by Asampson** [comment]
All changed on live site.
