### ISSUE TITLE
Subscription view - all staff listed

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#287]
When subscribing to a new module all module staff are listed above the module subscription button. 

![screen shot 2014-02-10 at 15 31 50](https://f.cloud.github.com/assets/1598231/2126986/9e269566-9268-11e3-8e62-8da42d976239.png)

Is there a way to remove this? This is much more cluttered than the current learning space and takes the roles from the category/system settings and not the module itself.

**Comment by ghost** [comment]
This won't be a problem once we have properly implemented user pictures (Which is happening once the theme has been updated).

There is the separate issue relating to user roles, which will be sorted in time for theme update.

I'm closing this as your reported issue, to do with the visual appearance of how staff are listed, will be fixed in the theme update. The other issue you a talking about, regarding all staff being listed, is a separate issue, and has meetings scheduled to fix, and is being discussed in another thread. @Asampson 

![screen shot 2014-02-17 at 11 51 12](https://f.cloud.github.com/assets/2537947/2184897/d640124a-97c9-11e3-9548-7b94ae6e27c2.png)
