### ISSUE TITLE
Force Download

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#35]
Files are currently set to force download, may be better to allow them to be diplsyed in browser. What say you @aaronmarruk 
![screen shot 2013-08-12 at 15 45 15](https://f.cloud.github.com/assets/1681436/948001/aa888f2e-035e-11e3-9aca-5cae5c0f306f.png)

**Comment by ghost** [comment]
There is a reason why it is set like this. It is to do with display issues on mobile browsers. This should really be tested by @learningtechnology.

I think forcing download actually forces mobile devices to display the media. Displaying "in browser" causes issues on mobiles. I think that's why it's set like that.

**Comment by Asampson** [comment]
Having issues with this for Film. It's meaning all their movie clips are downloading and they rather this was set to open as per old Learning Space.

**Comment by themarkness** [comment]
It appears that the option to Open has already been enabled. Both work on mobile. Am marking as resolved.
