### ISSUE TITLE
My profile settings (Students)

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#81]
My Profile settings should be taken off the settings list for students. Do students use the mail feature @damienh ?

**Comment by damienh** [comment]
@Asampson when you say my profile settings is this listed in the dropdown? Also in terms of mail feature do you mean the internal messaging in Moodle?

**Comment by Asampson** [comment]
Nope meaning the settings listed in the users settings side block. Yep I do mean the internal mail within Moodle.

**Comment by Asampson** [comment]
@damienh Here are the settings. @aaronmarruk @oscott  Can you see that this is needed? 

![screen shot 2013-10-07 at 14 34 42](https://f.cloud.github.com/assets/1598231/1280581/5acbc104-2f55-11e3-8d7c-0a54de2ae239.png)

**Comment by ghost** [comment]
I think the idea is we will provide an alternative to this block – i.e. create links on the page that do the stuff listed in the block.

Basically, we don't want the block because it is ugly – the unsubscribe option is the only child of "Course Administration" and those other links are already available elsewhere on the page I believe?

So what I will do is create an "Unsubscribe" link that is visable on every module page (Like in my original wireframes). That way we don't need the block. 

Does that sound ok? @Asampson

**Comment by Asampson** [comment]
Sounds good, at the moment the only option that is really needed in this block is the unsubscribe/subscribe option, hence wanting to get rid of the other options. 

Will your button also allow people to subscribe @aaronmarruk as this will be needed for pages that allow guest access but include forums etc?

At the moment students can access the messaging settings which is why I was suggesting hiding these settings from the student profile, which you can do within the admin settings. I still think we need to hide these until your button is ready, but need some CM before we can do this.

**Comment by themarkness** [comment]
Agreed @Asampson @oscott

**Comment by oscott** [comment]
perhaps on the frontpage where the courses are listed we could have an icon for each. Surely we can link to straight to this page http://learningspace.falmouth.ac.uk/enrol/self/unenrolself.php?enrolid=982 passing the course id number. ?

**Comment by oscott** [comment]
wont work - perhaps something in here: http://stackoverflow.com/questions/13345713/how-to-unenroll-user-from-a-course-with-php i'm still looking

**Comment by ghost** [comment]
Haha, welcome to my world @oscott

**Comment by ghost** [comment]
One way might be to look at the PHP for the "unsubscribe" link. Then trace the unsubscribe function, as presumeable the is a relative "subscribe" function. That might point us in the right direction. I will have a look if you want?

@oscott

**Comment by Asampson** [comment]
This request was only to hide part of this block. See highlighted section below. 
![screen shot 2013-10-09 at 14 20 01](https://f.cloud.github.com/assets/1598231/1297604/9a1ca170-30e5-11e3-8a76-80b3f3d85814.png)
Will change this.

**Comment by oscott** [comment]
nearly there... 

```
$contextunenrol = get_context_instance(CONTEXT_COURSE, $course->id);
role_unassign(0, $USER->id, 0, $contextunenrol->id);
add_to_log($course->id, 'course', 'unenrol', "view.php?id=$course->id", $USER->id);
```

**Comment by damienh** [comment]
will go over this Monday but here is snippet i found 

/Users/damienhogan/projects/moodle/moodle/enrol/self/unenrolself.php:
   45  }
   46  
   47: $PAGE->set_url('/enrol/self/unenrolself.php', array('enrolid'=>$instance->id));
   48  $PAGE->set_title($plugin->get_instance_name($instance));
   49  

8 matches across 4 files

**Comment by Asampson** [comment]
Any more progress with this @damienh and @oscott - still assigned to me so just checking.

**Comment by Asampson** [comment]
Any more progress with this @damienh and @oscott - still assigned to me so just checking.

**Comment by damienh** [comment]
@aaronmarruk to put together a proposal to hide settings block and reprint.

**Comment by ghost** [comment]
UPDATE Jan 2014: I'm not able to test this on my local install as the enrolments on my local machine are set up differently. I would appreciate if @themarkness or @damienh could help get this sorted.

**Comment by oscott** [comment]
This has been pulled by @aaronmarruk into 2.1 update - i shall change the milestone to reflect this. can @themarkness please have a look at aarons last message on his return.

**Comment by ghost** [comment]
My proposals above, regarding reprinting this block etc. cause several problems and I have some to the conclusion that it is more hassle than worth to "Reprint" these settings in a new block.

The main problems are:
1. Reprinting the block with jQuery doesn't work due to interference with YUI.
2. Different settings are sometimes available, for example, in forums.

**What I have done is hidden the unwanted settings for students, done in the theme.** This way, reported problems have been resolved and there are no repercussions etc.

There may be a way to solve this in the admin settings. If so, this can be reopened and assigned to an appropriate LT. My changes can easily be undone on the theme side.
